const songDiscoDiUks = {
    id: 3,
    title: "Disco di UKS (Disco Hokenshitsu)",
    cover: "images/cara-meminum-ramune.jpg", 
    src: "song/disco-di-uks.mp3",
    lyrics: [
        { time: 24, text: "Bel terakhir pun berbunyi ya yang haruskah kita mulai segera", isChant: false },
        { time: 31, text: "Bawa kalian yang masih di gedung sekolah cepat sana bergegaslah pulang", isChant: false },
        { time: 46, text: "Dari kaca jendela ruang guru kayaknya sudah tak ada bayangan orang", isChant: false },
        { time: 53, text: "Bawa reservasi hingga pagi hari hanya untuk kita berdua", isChant: false },
        { time: 60, text: "Kunci pintu rapat-rapat sekencang-kencangnya", isChant: false },
        { time: 64, text: "Sambungkan dengan laptopnya lalu menyalakan musik", isChant: false },
        { time: 68, text: "Ubahlah UKS menjadi ruang disko", isChant: false },
        { time: 71, text: "Mari kita menari di atas kasur", isChant: false },
        { time: 75, text: "Namun kakak dokter dansa saja", isChant: false },
        { time: 79, text: "Buang saja semua aturan keselamatan", isChant: false },
        { time: 82, text: "Yuk kita bergoyang ikut irama", isChant: false },
        { time: 86, text: "Ku menarik pinggangmu kiss kiss kiss me", isChant: false },
        { time: 90, text: "Cinta itu member only", isChant: false },
        { time: 125, text: "Dokter anak nakal entahlah ya", isChant: false },
        { time: 129, text: "Meski ku ditegur dengan halus", isChant: false },
        { time: 132, text: "Bukannya juga jadi cowok ya", isChant: false },
        { time: 136, text: "Inilah apa adanya hatiku", isChant: false },
        { time: 139, text: "Aku mencari masa muda", isChant: false },
        { time: 143, text: "Memang melihat dirimu ku hanya inginkan pancingan", isChant: false },
        { time: 147, text: "Sengaja sering pergi ke ruang UKS berpura-pura kepala sedang sakit", isChant: false },
        { time: 154, text: "Meski semua sedang kelas di pinggir pantai surga", isChant: false },
        { time: 161, text: "Wanita yang lebih tua memanjakanku", isChant: false },
        { time: 168, text: "Lampu kuning berganti bagaikan sihir", isChant: false },
        { time: 172, text: "Mimpi atau ilusimu", isChant: false },
        { time: 175, text: "Ingin tetap berjalan bersama", isChant: false },
        { time: 220, text: "Di depan orang lain kau guruku", isChant: false },
        { time: 224, text: "Tapi kalau berdua kamu pacarku", isChant: false },
        { time: 227, text: "Karena ini romansa rahasia", isChant: false },
        { time: 231, text: "Tanpa bilang siapa pun aku jadi ingin menari", isChant: false },
        { time: 238, text: "Ubahlah UKS menjadi ruang disko", isChant: false },
        { time: 241, text: "Mari kita menari di atas kasur", isChant: false },
        { time: 245, text: "Namun kakak dokter dansa dengan jas putih", isChant: false },
        { time: 253, text: "Buang saja semua aturan ke tempat sampah", isChant: false },
        { time: 257, text: "Yuk kita bergoyang ikut irama", isChant: false },
        { time: 261, text: "Ku menarik pinggangmu kiss kiss kiss me", isChant: false },
        { time: 267, text: "Cinta itu member only", isChant: false }
    ]
};