const songPertanda = {
    id: 1,
    title: "Pertanda (Kizashi)",
    cover: "images/cara-meminum-ramune.jpg", 
    src: "song/pertanda.mp3",
    lyrics: [
        { time: 30, text: "Sekarang kita sedang berkumpul di atas atap bangunan sekolah", isChant: false },
        { time: 37, text: "Bersama-sama menunggu terbitnya sang fajar, lalu", isChant: false },
        { time: 44, text: "Ya, melihat langit tanpa bintang, kita duduk di alas kardus", isChant: false },
        { time: 51, text: "Lalu membicarakan masa depan", isChant: false },
        { time: 57, text: "Kesedihan yang dalam, hari-hari yang dulu telah hilang", isChant: false },
        { time: 64, text: "Tak tahan dengan semua, terasa percuma", isChant: false },
        { time: 68, text: "Mencari cahaya yang bersinar 'tuk hari esok", isChant: false },
        { time: 71, text: "Memberi kita harapan", isChant: false },
        { time: 74, text: "Kamu di sini, aku di sini, dia di sini, dia juga di sini", isChant: false },
        { time: 81, text: "Langit timur berubah jadi putih, pagi yang baru akan tiba", isChant: false },
        { time: 88, text: "Kita menangis, kita pelukan, merangkul bahu, dan teruslah maju", isChant: false },
        { time: 95, text: "Bila disinari pertanda, sekali lagi kita semua akan menjadi kuat", isChant: false },
        { time: 119, text: "Ya, kota ini membuka mata dan memulai pergerakan", isChant: false },
        { time: 126, text: "Seakan ingin mengembalikan waktu yang telah hilang", isChant: false },
        { time: 133, text: "Lihat, matahari yang tak berubah", isChant: false },
        { time: 137, text: "Jika kita mengulurkan tangan kehangatannya pun bisa tertangkap", isChant: false },
        { time: 145, text: "Semuanya, jangan takut pada rasa sakit tak terlihat", isChant: false },
        { time: 152, text: "Air mata bagaimanapun pasti kering", isChant: false },
        { time: 156, text: "Cobalah percaya pada kata dari hatimu", isChant: false },
        { time: 160, text: "Memberi kita kekuatan", isChant: false },
        { time: 163, text: "Demi dirimu, demi diriku, demi dirinya, juga demi dia", isChant: false },
        { time: 170, text: "Angin yang lembut pun akan berhembus, hari yang bersinar 'kan tiba", isChant: false },
        { time: 177, text: "Hidup di sini, saling bersyukur, saling bertemu, saling mencintai", isChant: false },
        { time: 184, text: "Bila merasakan pertanda, kita semua ada di mana pun tak akan sendirian", isChant: false },
        { time: 214, text: "Kamu di sini, aku di sini, dia di sini, dia juga di sini", isChant: false },
        { time: 221, text: "Langit timur berubah jadi putih, pagi yang baru akan tiba", isChant: false },
        { time: 228, text: "Kita menangis, kita pelukan, merangkul bahu, dan teruslah maju", isChant: false },
        { time: 235, text: "Pertanda 'kan menjadi peta, kita yang hidup di jalan mimpi tidak akan menyerah", isChant: false }
    ]
};