const songSchoolyardsPuppy = {
    id: 2,
    title: "Schoolyards Puppy (Koutei no Koinu)",
    cover: "images/cara-meminum-ramune.jpg", 
    src: "song/Schoolyards-Puppy.mp3",
    lyrics: [
        { time: 1, text: "Di pojok halaman sekolah", isChant: false },
        { time: 5, text: "Ada seekor anak anjing", isChant: false },
        { time: 9, text: "Yang mendongak ke arah kelas", isChant: false },
        { time: 14, text: "Seperti mencari seseorang", isChant: false },
        { time: 17, text: "Sore hari yang tenang", isChant: false },

        { time: 45, text: "Waktu kelas ini sedang berlangsung", isChant: false },
        { time: 49, text: "Tiba-tiba aku memikirkan dirimu", isChant: false },
        { time: 53, text: "Pensilku mulai menggambar sketsa", isChant: false },
        { time: 57, text: "Wajah sampingmu tanpa sadar", isChant: false },
        { time: 60, text: "Kapan ku mulai tertarik kepadanya?", isChant: false },
        { time: 65, text: "Padahal dia cowok dari kelas lain", isChant: false },
        { time: 70, text: "Saat berpapasan dengan dia", isChant: false },
        { time: 74, text: "Dada jadi berdebar", isChant: false },
        
        { time: 79, text: "Langit biru yang di luar jendela", isChant: false },
        { time: 82, text: "Aku tatap sambil menyipitkan mata", isChant: false },
        { time: 87, text: "Memikirkan dirimu membuat hatiku", isChant: false },
        { time: 91, text: "Ini menjadi bingung", isChant: false },

        { time: 95, text: "Di pojok halaman sekolah", isChant: false },
        { time: 99, text: "Ada seekor anak anjing", isChant: false },
        { time: 103, text: "Yang mendongak ke arah kelas", isChant: false },
        { time: 107, text: "Seperti mencari seseorang", isChant: false },
        { time: 111, text: "Andai kau bisa berbicara", isChant: false },
        { time: 115, text: "Apa yang 'kan kita obrolkan?", isChant: false },
        { time: 120, text: "Cinta itu datang entah dari mananya", isChant: false },
        { time: 126, text: "Lalu berkeliaran tanpa arah", isChant: false },

        { time: 137, text: "Saat aku ditunjuk oleh guru", isChant: false },
        { time: 141, text: "Jadi terbata-bata tidak bisa menjawab", isChant: false },
        { time: 145, text: "'Oh unbelievable!', dia tak percaya", isChant: false },
        { time: 150, text: "Dan bilang, 'Ayo konsen!'", isChant: false },
        { time: 155, text: "Daripada rumus sin, cos, dan tangen", isChant: false },
        { time: 160, text: "Ku ingin lebih mengetahui jawaban", isChant: false },
        { time: 164, text: "Dari denyutan di lubuk hatiku", isChant: false },
        { time: 168, text: "Yang membuat terheran-heran", isChant: false },

        { time: 173, text: "Murid saat pelajaran olahraga", isChant: false },
        { time: 177, text: "Terlihat tidak peduli apa-apa", isChant: false },
        { time: 181, text: "Bahkan si pendatang kecil", isChant: false },
        { time: 185, text: "Mereka tidak memanggilnya", isChant: false },

        { time: 189, text: "Andaikan ku bisa bergegas", isChant: false },
        { time: 193, text: "Dengan tangan ini mendekap", isChant: false },
        { time: 197, text: "Kepalaku akan dielus", isChant: false },
        { time: 200, text: "Ingin selalu ada di sisimu", isChant: false },
        { time: 207, text: "Apa tujuanku ke sini?", isChant: false },
        { time: 210, text: "Ku bertanya di dalam hati", isChant: false },
        { time: 214, text: "Saat aku bahkan tidak menyadarinya", isChant: false },
        { time: 218, text: "Aku datang 'tuk bertemu denganmu", isChant: false },

        { time: 239, text: "Di pojok halaman sekolah", isChant: false },
        { time: 243, text: "Ada seekor anak anjing", isChant: false },
        { time: 248, text: "Yang mendongak ke arah kelas", isChant: false },
        { time: 252, text: "Seperti mencari seseorang", isChant: false },
        { time: 256, text: "Andai kau bisa berbicara", isChant: false },
        { time: 261, text: "Apa yang 'kan kita obrolkan?", isChant: false },
        { time: 265, text: "Cinta itu datang entah dari mananya", isChant: false },
        { time: 270, text: "Lalu berkeliaran tanpa arah", isChant: false }
    ]
};